[package]
name = "analytics"
version = "0.1.0"
authors = ["sisso <sissobr@gmail.com>"]
edition = "2018"

[dependencies]
time = "0.1"
chrono = "0.4.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.*"
rocket = "0.5.0-rc.1"
rusqlite = "0.14"
notify = "4.0.12"

