[package]
name = "analytics"
version = "0.1.0"
authors = ["sisso <sissobr@gmail.com>"]
edition = "2018"

[dependencies]
time = "0.1"
chrono = "0.4.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.*"
aurora_db = { version = "*", path = "../aurora_db" }
