[package]
name = "aurora-analytics"
version = "0.1.0"
authors = ["sisso <sissobr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.14"
time = "0.1"
chrono = "0.4.15"
error-chain = "0.12.4"