[package]
name = "aurora_db"
version = "0.1.0"
authors = ["sisso <sissobr@gmail.com>"]
edition = "2018"

[dependencies]
rusqlite = "0.14"
time = "0.1"
chrono = "0.4.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.*"